# Generated by Django 3.1.7 on 2021-06-11 01:43

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0001_initial'),
        ('jobshuborg_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='position_filled_by',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.expressions.Case, related_name='developer_position', to='login_app.developer'),
        ),
    ]
