# Generated by Django 3.1.7 on 2021-06-11 01:47

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('jobshubdev_app', '0001_initial'),
        ('login_app', '0001_initial'),
        ('jobshuborg_app', '0002_auto_20210610_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='position_filled_by',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.expressions.Case, related_name='developer_position', to='login_app.developer'),
        ),
        migrations.AlterField(
            model_name='position',
            name='position_framework',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='framework_position', to='jobshubdev_app.framework'),
        ),
        migrations.AlterField(
            model_name='position',
            name='position_language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='language_position', to='jobshubdev_app.language'),
        ),
    ]
