# Generated by Django 3.1.7 on 2021-06-11 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobshubdev_app', '0001_initial'),
        ('jobshuborg_app', '0003_auto_20210610_2147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='position_framework',
        ),
        migrations.AddField(
            model_name='position',
            name='position_framework',
            field=models.ManyToManyField(blank=True, null=True, related_name='framework_position', to='jobshubdev_app.Framework'),
        ),
        migrations.RemoveField(
            model_name='position',
            name='position_language',
        ),
        migrations.AddField(
            model_name='position',
            name='position_language',
            field=models.ManyToManyField(blank=True, null=True, related_name='language_position', to='jobshubdev_app.Language'),
        ),
    ]
