# Generated by Django 3.1.7 on 2021-06-11 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobshubdev_app', '0001_initial'),
        ('jobshuborg_app', '0004_auto_20210611_0309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='position_framework',
            field=models.ManyToManyField(blank=True, related_name='framework_position', to='jobshubdev_app.Framework'),
        ),
        migrations.AlterField(
            model_name='position',
            name='position_language',
            field=models.ManyToManyField(blank=True, related_name='language_position', to='jobshubdev_app.Language'),
        ),
    ]
