# Generated by Django 3.1.7 on 2021-06-12 04:25

import apps.messages_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messages_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messageorg',
            name='message_content',
            field=models.CharField(blank=True, max_length=255, validators=[apps.messages_app.models.ValidarLongitudMinima]),
        ),
    ]
