# Generated by Django 3.1.7 on 2021-06-12 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messages_app', '0002_auto_20210612_0025'),
    ]

    operations = [
        migrations.AddField(
            model_name='messageorg',
            name='readed_for_developer',
            field=models.CharField(default=False, max_length=8),
        ),
    ]
