# Generated by Django 3.1.7 on 2021-06-12 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messages_app', '0003_messageorg_readed_for_developer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messageorg',
            name='readed_for_developer',
            field=models.BooleanField(default=False, max_length=8),
        ),
    ]
