# Generated by Django 3.1.7 on 2021-06-12 08:09

import apps.messages_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messages_app', '0006_auto_20210612_0352'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_content', models.CharField(blank=True, max_length=255, validators=[apps.messages_app.models.ValidarLongitudMinima])),
                ('sender_id', models.CharField(max_length=10, validators=[apps.messages_app.models.ValidarLongitudMinima])),
                ('reciever_id', models.CharField(max_length=10, validators=[apps.messages_app.models.ValidarLongitudMinima])),
                ('readed', models.BooleanField(default=False, max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
