# Generated by Django 3.1.7 on 2021-06-12 08:28

import apps.messages_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messages_app', '0007_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='user_type',
            field=models.CharField(blank=True, max_length=10, validators=[apps.messages_app.models.ValidarLongitudMinima]),
        ),
    ]
