# Generated by Django 3.1.7 on 2021-06-13 03:06

import apps.messages_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messages_app', '0008_message_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messageorg',
            name='message_created_by',
        ),
        migrations.RemoveField(
            model_name='messageorg',
            name='message_to_developer',
        ),
        migrations.AlterField(
            model_name='message',
            name='user_type',
            field=models.CharField(max_length=10, validators=[apps.messages_app.models.ValidarLongitudMinima]),
        ),
        migrations.DeleteModel(
            name='MessageDev',
        ),
        migrations.DeleteModel(
            name='MessageOrg',
        ),
    ]
