# Generated by Django 3.1.7 on 2021-06-13 23:41

import apps.jobshubdev_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobshubdev_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biography',
            name='short_bio',
            field=models.CharField(blank=True, max_length=255, validators=[apps.jobshubdev_app.models.ValidarLongitudMinima]),
        ),
    ]
