# Generated by Django 3.1.7 on 2021-06-13 23:43

import apps.jobshubdev_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobshubdev_app', '0002_auto_20210613_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biography',
            name='short_bio',
            field=models.CharField(max_length=255, null=True, validators=[apps.jobshubdev_app.models.ValidarLongitudMinima]),
        ),
    ]
