# Generated by Django 3.1.7 on 2021-06-14 00:09

import apps.jobshubdev_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobshubdev_app', '0003_auto_20210613_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='biography',
            name='github_link',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[apps.jobshubdev_app.models.ValidarGithub]),
        ),
    ]
