# Generated by Django 3.1.7 on 2021-06-11 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0002_developer_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='match_proportion',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
