# Generated by Django 3.1.7 on 2021-06-12 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0003_developer_match_proportion'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='skills_number',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
