# Generated by Django 3.1.7 on 2021-06-13 23:41

import apps.login_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0004_developer_skills_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='address_name',
            field=models.CharField(max_length=50, validators=[apps.login_app.models.ValidarLongitudMinima]),
        ),
        migrations.AlterField(
            model_name='organization',
            name='address_name',
            field=models.CharField(max_length=50, validators=[apps.login_app.models.ValidarLongitudMinima]),
        ),
    ]
